# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a12efe42bca350893d6a916398b1d00ca9423f08698864566cc32c097a818e7c45b81d80f74aa1055265dba4b832b5784422e980e19c2a3b6bb0c464ff63561

test:
  secret_key_base: e7f3a697f7bc42f9d8f073e88534577a833a273a2521cfe082a248309bc5d95725e39d9a00d59b3bd616f1638728b8c54b0c1004dc1affc7d7a75dfd37d06c29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
